version: '3'

networks:
    webapp:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: app_nginx
        tty: true
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - mysql
        networks:
            - webapp
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_php
        tty: true
        volumes:
            - ./:/var/www/app
        ports:
            - "9001:9000"
        networks:
            - webapp

    mysql:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - webapp

